# Generated by Django 5.1.1 on 2024-09-27 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ingredients', models.JSONField()),
                ('instructions', models.JSONField()),
                ('cuisine_type', models.CharField(max_length=100)),
                ('photo_link', models.URLField(blank=True, max_length=500, null=True)),
                ('preparation_time', models.IntegerField(help_text='Preparation time in minutes')),
                ('cooking_time', models.IntegerField(help_text='Cooking time in minutes')),
                ('yields', models.IntegerField(help_text='Number of servings')),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_recipes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
